### index handler
GET http://localhost:8080/

### update handler
PATCH http://localhost:8080/
Content-Type: application/json

{
    "age": 20,
    "skill": ["Rust", "Go","Node.js"]
}


### shorten handler
POST http://localhost:9876/
Content-Type: application/json

{
    "url": "https://www.baidu.com"
}

### redirect handler
GET http://localhost:9876/1glSNn
